import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:front_end/models/complaint_model.dart';
import 'package:intl/intl.dart';

class PdfGeneratorService {
  
  Future<Uint8List> generateComplaintPDF(ComplaintModel complaint) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormat = DateFormat('dd MMM yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColors.green900,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'COMPLAINT TO FEDERAL OMBUDSPERSON',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Protection Against Harassment of Women at Workplace',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  'Generated by Legal Sathi on ${dateFormat.format(now)}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                  ),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 24),

          // To Address
          pw.Text(
            'To,',
            style: const pw.TextStyle(fontSize: 12),
          ),
          pw.Text(
            'The Federal Ombudsperson',
            style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
          ),
          pw.Text(
            'Protection Against Harassment of Women at Workplace',
            style: const pw.TextStyle(fontSize: 12),
          ),
          pw.Text(
            'Islamabad, Pakistan',
            style: const pw.TextStyle(fontSize: 12),
          ),

          pw.SizedBox(height: 24),

          // Applicant Details Section
          _buildSection('APPLICANT DETAILS:', [
            {'label': 'Name', 'value': complaint.fullName ?? 'N/A'},
            {'label': 'CNIC', 'value': complaint.cnic ?? 'N/A'},
            {'label': 'Phone', 'value': complaint.phone ?? 'N/A'},
            {'label': 'Email', 'value': complaint.email ?? 'N/A'},
            {'label': 'Workplace', 'value': complaint.workplace ?? 'N/A'},
            {'label': 'Designation', 'value': complaint.designation ?? 'N/A'},
            {'label': 'City', 'value': complaint.city ?? 'N/A'},
          ]),

          pw.SizedBox(height: 20),

          // Incident Details Section
          _buildSection('INCIDENT DETAILS:', [
            {'label': 'Date of Incident', 'value': complaint.incidentDate ?? 'N/A'},
            {'label': 'Type of Harassment', 'value': complaint.harassmentType ?? 'N/A'},
          ]),

          pw.SizedBox(height: 16),

          // Description
          pw.Text(
            'DETAILED DESCRIPTION:',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.green900,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              complaint.description ?? 'No description provided',
              style: const pw.TextStyle(fontSize: 11),
              textAlign: pw.TextAlign.justify,
            ),
          ),

          pw.SizedBox(height: 20),

          // Accused Person Section
          _buildSection('ACCUSED PERSON:', [
            {'label': 'Name', 'value': complaint.accusedName ?? 'N/A'},
            {'label': 'Designation', 'value': complaint.accusedDesignation ?? 'N/A'},
          ]),

          pw.SizedBox(height: 20),

          // Evidence Files Section
          if (complaint.evidenceFiles != null && complaint.evidenceFiles!.isNotEmpty) ...[
            pw.Text(
              'EVIDENCE FILES ATTACHED:',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.green900,
              ),
            ),
            pw.SizedBox(height: 8),
            ...complaint.evidenceFiles!.map((file) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 4, left: 8),
              child: pw.Row(
                children: [
                  pw.Container(
                    width: 4,
                    height: 4,
                    decoration: const pw.BoxDecoration(
                      color: PdfColors.green900,
                      shape: pw.BoxShape.circle,
                    ),
                  ),
                  pw.SizedBox(width: 8),
                  pw.Expanded(
                    child: pw.Text(
                      '${file.fileName} (${file.fileType}) - ${(file.fileSize ?? 0) ~/ 1024} KB',
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ),
                ],
              ),
            )),
            pw.SizedBox(height: 20),
          ],

          // Declaration
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'DECLARATION:',
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  'I hereby declare that the information provided in this complaint is true and correct to the best of my knowledge. I understand that providing false information may result in legal consequences.',
                  style: const pw.TextStyle(fontSize: 10),
                  textAlign: pw.TextAlign.justify,
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 32),

          // Signature Section
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    width: 200,
                    height: 1,
                    color: PdfColors.black,
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'Complainant Signature',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                  pw.Text(
                    complaint.fullName ?? 'N/A',
                    style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
                  ),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    width: 150,
                    height: 1,
                    color: PdfColors.black,
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'Date',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                  pw.Text(
                    dateFormat.format(now),
                    style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
                  ),
                ],
              ),
            ],
          ),

          pw.SizedBox(height: 32),

          // Footer
          pw.Divider(color: PdfColors.grey400),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Legal Sathi App',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
              pw.Text(
                'Complaint ID: ${complaint.complaintId ?? "N/A"}',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            ],
          ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildSection(String title, List<Map<String, String>> items) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.green900,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColors.grey400),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: items.map((item) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 6),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.SizedBox(
                    width: 120,
                    child: pw.Text(
                      '${item['label']!}:',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                  pw.Expanded(
                    child: pw.Text(
                      item['value']!,
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ),
                ],
              ),
            )).toList(),
          ),
        ),
      ],
    );
  }
}

