-- User Documents Table
-- Stores all documents uploaded/generated by users
-- Each user can only see their own documents

CREATE TABLE IF NOT EXISTS user_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Document Info
    filename TEXT NOT NULL,
    title TEXT,
    description TEXT,
    document_type VARCHAR(50),  -- "complaint", "template", "generated_pdf", "uploaded", etc.
    
    -- File Storage
    storage_path TEXT NOT NULL,  -- Path in Supabase storage
    file_url TEXT NOT NULL,      -- Public/private URL
    file_size INTEGER,           -- Size in bytes
    mime_type VARCHAR(100),      -- e.g., application/pdf, text/plain
    
    -- Metadata
    source_module VARCHAR(50),   -- Which module generated this (women_harassment, cyber_law, etc.)
    related_complaint_id UUID,   -- Link to complaint if applicable
    tags JSONB,                  -- Array of tags for organization ["urgent", "complaint", "template"]
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Soft Delete
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Indexes
CREATE INDEX idx_user_documents_user_id ON user_documents(user_id);
CREATE INDEX idx_user_documents_user_id_created ON user_documents(user_id, created_at DESC);
CREATE INDEX idx_user_documents_document_type ON user_documents(user_id, document_type);
CREATE INDEX idx_user_documents_source_module ON user_documents(user_id, source_module);
CREATE INDEX idx_user_documents_is_deleted ON user_documents(user_id, is_deleted);

-- Enable RLS
ALTER TABLE user_documents ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can view only their own documents
CREATE POLICY "Users can view own documents"
ON user_documents FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own documents
CREATE POLICY "Users can insert own documents"
ON user_documents FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can update their own documents
CREATE POLICY "Users can update own documents"
ON user_documents FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Users can soft delete their own documents
CREATE POLICY "Users can soft delete own documents"
ON user_documents FOR UPDATE
USING (auth.uid() = user_id AND is_deleted = false)
WITH CHECK (auth.uid() = user_id);
