"""
Helper module for managing user-specific documents.
Documents are personal files that users generate, download, or upload.
Examples: complaint PDFs, filled templates, generated documents, etc.
"""

from typing import List, Dict, Optional, Any
from pydantic import BaseModel
from datetime import datetime

class UserDocument(BaseModel):
    """Model for a user's document"""
    id: str
    user_id: str
    filename: str
    title: Optional[str] = None
    description: Optional[str] = None
    document_type: str  # "complaint", "template", "generated_pdf", "uploaded", etc.
    file_url: str
    file_size: Optional[int] = None  # bytes
    mime_type: Optional[str] = None
    source_module: Optional[str] = None  # women_harassment, cyber_law, etc.
    related_complaint_id: Optional[str] = None
    tags: Optional[List[str]] = None
    created_at: str  # ISO format
    updated_at: Optional[str] = None
    is_deleted: bool = False


class UserDocumentsResponse(BaseModel):
    """Response model for user documents list"""
    user_id: str
    documents: List[UserDocument]
    total_count: int
    storage_quota_bytes: int = 100 * 1024 * 1024  # 100 MB default
    used_bytes: int = 0


class DocumentUploadRequest(BaseModel):
    """Request to save a document for user"""
    filename: str
    title: Optional[str] = None
    description: Optional[str] = None
    document_type: str  # Required: complaint, template, generated_pdf, uploaded
    file_size: int
    mime_type: str
    source_module: Optional[str] = None
    related_complaint_id: Optional[str] = None
    tags: Optional[List[str]] = None


class DocumentMetadata(BaseModel):
    """Metadata for displaying a document"""
    id: str
    filename: str
    title: Optional[str]
    document_type: str
    file_size: Optional[int]
    created_at: str
    icon: str
    badge_color: str


# Document type information
DOCUMENT_TYPES = {
    "complaint": {
        "display_name": "Complaint Document",
        "icon": "📋",
        "color": "red",
        "description": "FIR or complaint documents"
    },
    "template": {
        "display_name": "Template",
        "icon": "📑",
        "color": "blue",
        "description": "Filled or blank templates"
    },
    "generated_pdf": {
        "display_name": "Generated PDF",
        "icon": "📄",
        "color": "purple",
        "description": "PDFs generated by the app"
    },
    "uploaded": {
        "display_name": "Uploaded File",
        "icon": "📤",
        "color": "green",
        "description": "Files uploaded by user"
    },
    "evidence": {
        "display_name": "Evidence",
        "icon": "🔍",
        "color": "orange",
        "description": "Evidence documents"
    }
}


def get_document_icon(doc_type: str) -> str:
    """Get icon for document type"""
    return DOCUMENT_TYPES.get(doc_type, {}).get("icon", "📄")


def get_document_color(doc_type: str) -> str:
    """Get badge color for document type"""
    return DOCUMENT_TYPES.get(doc_type, {}).get("color", "gray")


def get_document_display_name(doc_type: str) -> str:
    """Get display name for document type"""
    return DOCUMENT_TYPES.get(doc_type, {}).get("display_name", doc_type)


def format_file_size(size_bytes: int) -> str:
    """Format file size to human readable format"""
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.1f} MB"


def build_document_metadata(
    doc_id: str,
    filename: str,
    title: Optional[str],
    doc_type: str,
    file_size: Optional[int],
    created_at: str
) -> DocumentMetadata:
    """Build metadata for document display"""
    return DocumentMetadata(
        id=doc_id,
        filename=filename,
        title=title or filename,
        document_type=doc_type,
        file_size=file_size,
        created_at=created_at,
        icon=get_document_icon(doc_type),
        badge_color=get_document_color(doc_type)
    )
